<cfoutput>
	<tr>
		<td>#transaction.date1#</td>
		<td>#transaction.reference1#</td>
		<td>#transaction.amount1#</td>
		<td>#transaction.date2#</td> 
		<td>#transaction.reference2#</td>
		<td>#transaction.amount2#</td>
	</tr>
</cfoutput>